# exec: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update && helm upgrade --install --create-namespace --namespace prometheus prometheus prometheus-community/kube-prometheus-stack -f prometheus.yaml
coreDns:
  enabled: true
prometheusOperator:
  enabled: true
  namespaces: {}
prometheus:
  enabled: true
  ingress:
    enabled: false
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 90d
    replicas: 1
    shards: 1
kubeEtcd:
  enabled: true
