apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kitchen-aid.fullname" . }}
  labels:
    {{- include "kitchen-aid.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
